import SwiftUI

/// Named colours used by the app.
/// Note: `progressFilled`, `progressPending`, and `summaryRemaining` are
/// automatically generated by Xcode from Assets.xcassets.
extension Color {
    /// App background: pure OLED black (#000000) in dark mode, pure white (#FFFFFF) in light mode.
    static let background = Color(uiColor: UIColor { traitCollection in
        traitCollection.userInterfaceStyle == .dark ? .black : .white
    })
}